name: polygnn
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - defaults::python=3.10
  - pytorch
  - torchvision
  - sage=10.0
  - pytorch-cuda=11.7
  - pyg=2.3
  - pytorch-scatter
  - pytorch-sparse
  - pytorch-cluster
  - torchmetrics
  - rtree
  - pip
  - pip:
      - abspy==0.2.6
      - hydra-core
      - hydra-colorlog
      - omegaconf
      - trimesh
      - tqdm
      - wandb
      - plyfile
